spring:
  application:
    name: itoken-config
  boot:
    admin:
      client:
        url: http://192.168.57.133:8084
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/juno4717/itoken
          search-paths: itoken-configuration
          username: juno4717
          password: 0321123qQ
          skip-ssl-validation: true
server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.57.133:8761/eureka/