spring:
  application:
    name: itoken-zipkin
  boot:
    admin:
      client:
        url: http://192.168.57.133:8084

server:
  port: 9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.57.133:8761/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false