spring:
  application:
    name: itoken-eureka
  boot:
    admin:
      client:
        url: http://192.168.57.133:8084
zipkin:
  base-url: http://192.168.57.133:9411
server:
  port: 8761

eureka:
  instance:
    hostname: 192.168.57.133
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.57.133:8761/eureka/,http://192.168.57.133:8761/eureka/,http://192.168.57.133:8761/eureka/