spring:
  application:
    name: itoken-zuul
  boot:
    admin:
      client:
        url: http://192.168.57.133:8084
zipkin:
  base-url: http://192.168.57.133:9411
server:
  port: 8769

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.57.133:8761/eureka/

zuul:
  routes:
    api-a:
      path: /api/a/**
      serviceId: hello-spring-cloud-web-admin-ribbon
    api-b:
      path: /api/b/**
      serviceId: hello-spring-cloud-web-admin-feign